### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ghost** [cpacm/MoeMusic#2]
为什么没声音啊？而且，操作稍微频繁就ANR了。我的手机是Nubia Z9 MAX,系统6.0

**Comment by cpacm** [comment]
没声音的时候看看播放界面的进度条有没有在前进，萌否的音乐资源不是很稳定，偶尔会访问不到。
ANR的话方便能看看crash文件吗？文件在安卓应用数据下的com.cpacm.moemusic的cache文件夹下

**Comment by cpacm** [comment]
已发布新的版本，请在 设置->检查更新 更新版本
