### ISSUE TITLE
请问代码中有个core 抓个依赖包 是什么 从哪里来的

### ISSUE THREAD

**Issue by yuzhongrong** [cpacm/MoeMusic#3]
请问代码中有个core 这个依赖包 是什么 从哪里来的 

具体的包名：com.cpacm.core  这个是萌否开发官网的SDK 吗  我没有找到下载地址啊

**Comment by cpacm** [comment]
不是，这个是依赖模块，也是源代码放在根目录下，跟app目录同级

**Comment by yuzhongrong** [comment]
我知道抓个是个依赖模块  我想知道这个依赖模块 是自己写的还是 一个怎么回事 从哪来的 名字

**Comment by yuzhongrong** [comment]
并且这个依赖模块有哪些功能 负责干什么的

**Comment by cpacm** [comment]
自己写的，负责网络层和数据层

**Comment by yuzhongrong** [comment]
哦 我知道了 这样说我就明白了 谢谢啊

**Comment by yuzhongrong** [comment]
你这个APP质量比较好  基本没有什么报错和ANR 适合借鉴

**Comment by yuzhongrong** [comment]
那个 认证方法除了 萌否网 我要是换成其他网应该也是同一个道理吧  按照这个办法也可以？

**Comment by cpacm** [comment]
都可以的，oauth标准的认证方式基本上都能用

**Comment by yuzhongrong** [comment]
哦

**Comment by yuzhongrong** [comment]
APP的 加载图片速度很慢 是萌否那边服务器配置有问题 还是什么问题

**Comment by yuzhongrong** [comment]
retrofit2 有使用吗？看你没有加入依赖啊

**Comment by cpacm** [comment]
因为萌否服务器上的小图放在手机上显示很模糊，所以我就直接用的大图了。
retrofit2的依赖写在core下的gradle里

**Comment by yuzhongrong** [comment]
哦  找这么说 你这个项目是一套东西啊 如果研究透了 可以用在其他任何项目开发  比如 网络音乐播放器，视频播放器  等等？

**Comment by yuzhongrong** [comment]
只是 请求URL 和返回的json不一样而已处理不一样 其他都差不多啊

**Comment by yuzhongrong** [comment]
你这个事个框架性的 APP吧

**Comment by cpacm** [comment]
开发一般的app这个框架应该就足够了。不过app最重要的还是UI上的设计，这一块每个app都是不一样的。

**Comment by yuzhongrong** [comment]
恩  我是说框架哦 基本足够了 包括请求 等  当然 那些返回的数据对象可能要自己封装 自己处理 自己定义啊
